// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package queuerpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Type int32

const (
	Type_UNARY         Type = 0
	Type_CLIENT_STREAM Type = 1
	Type_SERVER_STREAM Type = 2
)

var Type_name = map[int32]string{
	0: "UNARY",
	1: "CLIENT_STREAM",
	2: "SERVER_STREAM",
}

var Type_value = map[string]int32{
	"UNARY":         0,
	"CLIENT_STREAM": 1,
	"SERVER_STREAM": 2,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

// Message is an rpc message sent over a message-queue it is used as a client side request and server side response
type Message struct {
	// id is the message id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// type is the message type
	Type Type `protobuf:"varint,2,opt,name=type,proto3,enum=queuerpc.Type" json:"type,omitempty"`
	// method is the method to call
	Method string `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	// reply_to is the reply queue to send the response to
	ReplyTo string `protobuf:"bytes,4,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	// body is the message body
	Body []byte `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	// metadata is a map of key value pairs
	Metadata map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Error is set if the message failed to be processed
	Error *Error `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	// unix timestamp in milliseconds
	Timestamp            int64    `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Message) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_UNARY
}

func (m *Message) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Message) GetReplyTo() string {
	if m != nil {
		return m.ReplyTo
	}
	return ""
}

func (m *Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Message) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Message) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Message) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// Error is an rpc error
type Error struct {
	// message is the error message
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// code is the error code
	Code                 uint32   `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterEnum("queuerpc.Type", Type_name, Type_value)
	proto.RegisterType((*Message)(nil), "queuerpc.Message")
	proto.RegisterMapType((map[string]string)(nil), "queuerpc.Message.MetadataEntry")
	proto.RegisterType((*Error)(nil), "queuerpc.Error")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x51, 0x4d, 0x4b, 0xe3, 0x40,
	0x18, 0xde, 0xc9, 0x47, 0x93, 0xbc, 0xdd, 0x74, 0xbb, 0xc3, 0xb2, 0xcc, 0x2e, 0x4a, 0x43, 0x41,
	0x08, 0x1e, 0x52, 0xa8, 0x88, 0xc5, 0x9e, 0xaa, 0xe4, 0x20, 0xd8, 0x1e, 0xa6, 0x51, 0xd0, 0x4b,
	0x49, 0x9b, 0xa1, 0x0d, 0x36, 0x4e, 0x9c, 0x4e, 0x84, 0xfc, 0x3e, 0xff, 0x98, 0x64, 0x92, 0x58,
	0xbc, 0x3d, 0x1f, 0xf3, 0xcc, 0x3b, 0xef, 0x33, 0xe0, 0x66, 0xec, 0x70, 0x88, 0xb7, 0x2c, 0xc8,
	0x05, 0x97, 0x1c, 0xdb, 0x6f, 0x05, 0x2b, 0x98, 0xc8, 0x37, 0xc3, 0x0f, 0x0d, 0xac, 0x79, 0xed,
	0xe1, 0x1e, 0x68, 0x69, 0x42, 0x90, 0x87, 0x7c, 0x87, 0x6a, 0x69, 0x82, 0x87, 0x60, 0xc8, 0x32,
	0x67, 0x44, 0xf3, 0x90, 0xdf, 0x1b, 0xf7, 0x82, 0x36, 0x14, 0x44, 0x65, 0xce, 0xa8, 0xf2, 0xf0,
	0x5f, 0xe8, 0x64, 0x4c, 0xee, 0x78, 0x42, 0x74, 0x95, 0x6b, 0x18, 0xfe, 0x07, 0xb6, 0x60, 0xf9,
	0xbe, 0x5c, 0x49, 0x4e, 0x0c, 0xe5, 0x58, 0x8a, 0x47, 0x1c, 0x63, 0x30, 0xd6, 0x3c, 0x29, 0x89,
	0xe9, 0x21, 0xff, 0x27, 0x55, 0x18, 0x4f, 0xc1, 0xce, 0x98, 0x8c, 0x93, 0x58, 0xc6, 0xa4, 0xe3,
	0xe9, 0x7e, 0x77, 0x3c, 0x38, 0x8e, 0x6b, 0xde, 0x17, 0xcc, 0x9b, 0x13, 0xe1, 0xab, 0x14, 0x25,
	0xfd, 0x0a, 0xe0, 0x33, 0x30, 0x99, 0x10, 0x5c, 0x10, 0xcb, 0x43, 0x7e, 0x77, 0xfc, 0xeb, 0x98,
	0x0c, 0x2b, 0x99, 0xd6, 0x2e, 0x3e, 0x01, 0x47, 0xa6, 0x19, 0x3b, 0xc8, 0x38, 0xcb, 0x89, 0xed,
	0x21, 0x5f, 0xa7, 0x47, 0xe1, 0xff, 0x14, 0xdc, 0x6f, 0xf7, 0xe3, 0x3e, 0xe8, 0x2f, 0xac, 0x6c,
	0xea, 0xa8, 0x20, 0xfe, 0x03, 0xe6, 0x7b, 0xbc, 0x2f, 0xea, 0x42, 0x1c, 0x5a, 0x93, 0x6b, 0x6d,
	0x82, 0x86, 0x97, 0x60, 0xaa, 0x51, 0x98, 0x80, 0xd5, 0x34, 0xdd, 0x04, 0x5b, 0x5a, 0x6d, 0xbd,
	0xe1, 0x49, 0x9d, 0x75, 0xa9, 0xc2, 0xe7, 0x57, 0x60, 0x54, 0x55, 0x62, 0x07, 0xcc, 0x87, 0xc5,
	0x8c, 0x3e, 0xf5, 0x7f, 0xe0, 0xdf, 0xe0, 0xde, 0xde, 0xdf, 0x85, 0x8b, 0x68, 0xb5, 0x8c, 0x68,
	0x38, 0x9b, 0xf7, 0x51, 0x25, 0x2d, 0x43, 0xfa, 0x18, 0xd2, 0x56, 0xd2, 0x6e, 0x06, 0xcf, 0xa7,
	0xdb, 0x54, 0xee, 0x8a, 0x75, 0xb0, 0xe1, 0xd9, 0x28, 0x2e, 0x24, 0xcf, 0x26, 0x92, 0x89, 0x51,
	0xbb, 0xf8, 0xba, 0xa3, 0xfe, 0xf9, 0xe2, 0x33, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x1b, 0xfb, 0x8b,
	0xf8, 0x01, 0x00, 0x00,
}
