// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package queuerpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Message is an rpc message sent over a message-queue it is used as a client side request and server side response
type Message struct {
	// id is the message id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// method is the method to call
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// body is the message body
	Body []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	// metadata is a map of key value pairs
	Metadata map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Error is set if the message failed to be processed
	Error *Error `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	// unix timestamp in milliseconds
	Timestamp            int64    `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Message) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Message) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Message) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Message) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// Error is an rpc error
type Error struct {
	// message is the error message
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// code is the error code
	Code                 uint32   `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "queuerpc.Message")
	proto.RegisterMapType((map[string]string)(nil), "queuerpc.Message.MetadataEntry")
	proto.RegisterType((*Error)(nil), "queuerpc.Error")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x50, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x65, 0x93, 0xa6, 0x1f, 0x53, 0xab, 0x32, 0x88, 0x2c, 0xa2, 0x34, 0x14, 0x84, 0x9c, 0x52,
	0xa8, 0x08, 0xc5, 0xde, 0x84, 0x1e, 0x7b, 0xd9, 0xa3, 0xb7, 0x4d, 0x76, 0x68, 0x83, 0xae, 0x1b,
	0x37, 0x1b, 0x21, 0x77, 0x7f, 0xb8, 0x24, 0xd9, 0x58, 0xbc, 0xbd, 0xf7, 0x66, 0xdf, 0xbe, 0x79,
	0x03, 0x0b, 0x4d, 0x55, 0x25, 0x8f, 0x94, 0x96, 0xd6, 0x38, 0x83, 0xd3, 0xaf, 0x9a, 0x6a, 0xb2,
	0x65, 0xbe, 0xfa, 0x09, 0x60, 0x72, 0xe8, 0x67, 0x78, 0x09, 0x41, 0xa1, 0x38, 0x8b, 0x59, 0x32,
	0x13, 0x41, 0xa1, 0xf0, 0x16, 0xc6, 0x9a, 0xdc, 0xc9, 0x28, 0x1e, 0x74, 0x9a, 0x67, 0x88, 0x30,
	0xca, 0x8c, 0x6a, 0x78, 0x18, 0xb3, 0xe4, 0x42, 0x74, 0x18, 0x77, 0x30, 0xd5, 0xe4, 0xa4, 0x92,
	0x4e, 0xf2, 0x51, 0x1c, 0x26, 0xf3, 0xcd, 0x32, 0x1d, 0x42, 0x52, 0x1f, 0x90, 0x1e, 0xfc, 0x8b,
	0xfd, 0xa7, 0xb3, 0x8d, 0xf8, 0x33, 0xe0, 0x23, 0x44, 0x64, 0xad, 0xb1, 0x3c, 0x8a, 0x59, 0x32,
	0xdf, 0x5c, 0x9d, 0x9d, 0xfb, 0x56, 0x16, 0xfd, 0x14, 0xef, 0x61, 0xe6, 0x0a, 0x4d, 0x95, 0x93,
	0xba, 0xe4, 0xe3, 0x98, 0x25, 0xa1, 0x38, 0x0b, 0x77, 0x3b, 0x58, 0xfc, 0xfb, 0x1f, 0xaf, 0x21,
	0x7c, 0xa7, 0xc6, 0xf7, 0x69, 0x21, 0xde, 0x40, 0xf4, 0x2d, 0x3f, 0x6a, 0xf2, 0x7d, 0x7a, 0xf2,
	0x12, 0x6c, 0xd9, 0xea, 0x19, 0xa2, 0x2e, 0x0a, 0x39, 0x4c, 0xfc, 0xa9, 0xbc, 0x71, 0xa0, 0x6d,
	0xeb, 0xdc, 0xa8, 0xde, 0xbb, 0x10, 0x1d, 0x7e, 0x5d, 0xbe, 0x3d, 0x1c, 0x0b, 0x77, 0xaa, 0xb3,
	0x34, 0x37, 0x7a, 0x2d, 0x6b, 0x67, 0xf4, 0xd6, 0x91, 0x5d, 0x0f, 0xfb, 0x67, 0xe3, 0xee, 0xde,
	0x4f, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x9f, 0x23, 0x22, 0x80, 0x01, 0x00, 0x00,
}
